ALTER TABLE "inquiries" ADD COLUMN IF NOT EXISTS "note" TEXT;
ALTER TABLE "inquiries" ADD COLUMN IF NOT EXISTS "contactedAt" TIMESTAMP(3);
ALTER TABLE "inquiries" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
